data_sources = [
    [
        "https://caraghnurseries.ie/product-category/all-trees-and-plants/bamboo/",
        "Bamboo",
    ],
    [
        "https://caraghnurseries.ie/product-category/all-trees-and-plants/all-climbers/",
        "Climber",
    ],
    [
        "https://caraghnurseries.ie/product-category/all-trees-and-plants/fruit-new/",
        "Fruit",
    ],
    [
        "https://caraghnurseries.ie/product-category/all-trees-and-plants/grasses-new/",
        "Grasses & Ferns",
    ],
    [
        "https://caraghnurseries.ie/product-category/all-trees-and-plants/hedging-new/",
        "Hedging",
    ],
    [
        "https://caraghnurseries.ie/product-category/all-trees-and-plants/all-plants-new/",
        "Perennials",
    ],
    [
        "https://caraghnurseries.ie/product-category/all-trees-and-plants/shrubs-new/",
        "Shrubs",
    ],
    [
        "https://caraghnurseries.ie/product-category/all-trees-and-plants/all-topiary-shaped-trees-new/",
        "Topiary",
    ],
    [
        "https://caraghnurseries.ie/product-category/all-trees-and-plants/all-trees/",
        "Trees",
    ],
]
