data_sources = [
    [
        "https://www.quickcrop.ie/hedging-plants/",
        "Hedging",
    ],
    [
        "https://www.quickcrop.ie/category/native-specimen-trees/",
        "Trees",
    ],
    [
        "https://www.quickcrop.ie/category/flowering-perennials/",
        "Perennials",
    ],
    [
        "https://www.quickcrop.ie/category/grasses-and-ferns/",
        "Grasses & Ferns",
    ],
    [
        "https://www.quickcrop.ie/category/rhubarb-crowns/",
        "Fruit",
    ],
    [
        "https://www.quickcrop.ie/category/soft-fruit/",
        "Fruit",
    ],
    [
        "https://www.quickcrop.ie/category/fruit-trees/",
        "Fruit",
    ],
]
